### ISSUE TITLE
ZeroDivisionError в LCM_NN_N

### ISSUE THREAD

**Issue by hacknullchainik** [hacknullchainik/DMATH_1306#15]
![image](https://user-images.githubusercontent.com/89996352/161402614-da65a2ab-5c00-4748-a8cc-26fa2585f9e8.png)

бросается исключение, хотя должно задаваться как в питоне:
![image](https://user-images.githubusercontent.com/89996352/161402568-47e866b2-6295-48cb-ae14-23f437a26578.png)

**Comment by W1nt3ryyy** [comment]
ошибку с 0 исправил.
есть проблема в функции MUL_NN_N(умножение натуральных чисел)
![image](https://user-images.githubusercontent.com/94673375/161421480-3f155faa-5e2e-4f3c-81a2-fe79841c934f.png)

**Comment by hellsys** [comment]
починено 
![image](https://user-images.githubusercontent.com/94673102/161443792-946c0d4a-5713-421f-9e54-6d5697cc99e3.png)
