### ISSUE TITLE
SUB_ZZ_Z не работает

### ISSUE THREAD

**Issue by hacknullchainik** [hacknullchainik/DMATH_1306#16]
cхема a - b
![image](https://user-images.githubusercontent.com/89996352/161404289-5abc60dd-4322-4b72-8b7a-05bec417e2d1.png)

**Comment by hacknullchainik** [comment]
![image](https://user-images.githubusercontent.com/89996352/161428159-14feabfc-de13-47d5-93dc-bd573b887efd.png)

**Comment by hellsys** [comment]
теперь работает
