### ISSUE TITLE
MOD_ZZ_Z not working properly

### ISSUE THREAD

**Issue by hacknullchainik** [hacknullchainik/DMATH_1306#18]
![image](https://user-images.githubusercontent.com/89996352/161404848-46cf1dff-b366-44cc-852c-c540910a22f8.png)

**Comment by hacknullchainik** [comment]
![image](https://user-images.githubusercontent.com/89996352/161404863-8fbc863f-bb8a-4de5-8233-c6e54767b65a.png)

**Comment by hacknullchainik** [comment]
![image](https://user-images.githubusercontent.com/89996352/161404874-74595c5e-b4b7-47c0-aa65-674b0623ff4b.png)
![image](https://user-images.githubusercontent.com/89996352/161404877-6965dcc7-5dc2-4f71-bb3a-82fa6c561f7c.png)

**Comment by doal116** [comment]
error found, function DIV_ZZ_Z is not returning the right value for quotient. 674 // 87 = 7 but DIV_ZZ_Z returns 8.
![image](https://user-images.githubusercontent.com/90492542/161422061-bdc94c9e-a88d-4d22-9a88-34ad629444d4.png)

**Comment by doal116** [comment]
which affects the last result of my function

**Comment by doal116** [comment]
function fixed 
![image](https://user-images.githubusercontent.com/90492542/161442490-77430d7a-a609-467d-9e76-ab44be342e48.png)
