### ISSUE TITLE
INT_Q_B ошибки в работе

### ISSUE THREAD

**Issue by hacknullchainik** [hacknullchainik/DMATH_1306#20]
вероятно, вызваны ошибками из RED_Q_Q
запускай тесты
![image](https://user-images.githubusercontent.com/89996352/161407418-3a2020ec-bfac-4f40-b639-8b2f162987fb.png)

**Comment by W1nt3ryyy** [comment]
ошибка исправлена с обходом ошибки в RED_Q_Q.
