### ISSUE TITLE
TRANS_Z_Q не работает 

### ISSUE THREAD

**Issue by hacknullchainik** [hacknullchainik/DMATH_1306#21]
![image](https://user-images.githubusercontent.com/89996352/161407666-61ef2830-fdc0-4ab9-8886-1dd3c15fca26.png)
![image](https://user-images.githubusercontent.com/89996352/161407678-fe7526b6-36ce-4f98-9af8-047a94cfeeaa.png)
я хз как ты это добро кастуешь там, но вот сам факт

**Comment by hellsys** [comment]
исправлено
