### ISSUE TITLE
SUB_QQ_Q not working

### ISSUE THREAD

**Issue by hacknullchainik** [hacknullchainik/DMATH_1306#24]
![image](https://user-images.githubusercontent.com/89996352/161408513-c76917d4-be28-48a8-b632-fe078e44210c.png)

**Comment by doal116** [comment]
error found in function LCM_NN_N
![Screenshot 2022-04-03 103714](https://user-images.githubusercontent.com/90492542/161416874-36f5831d-e128-4d10-a97f-a3aaf01ec784.png)
