### ISSUE TITLE
DIV_QQ_Q кидает исключение ZeroDivisionError

### ISSUE THREAD

**Issue by hacknullchainik** [hacknullchainik/DMATH_1306#25]
![image](https://user-images.githubusercontent.com/89996352/161408884-028e416e-57e3-4639-8772-c17a27b317a6.png)

**Comment by W1nt3ryyy** [comment]
ошибка выдается из-за функции RED_Q_Q

**Comment by W1nt3ryyy** [comment]
все исправлено
