### ISSUE TITLE
Обход арифметики больших чисел в DIV_NN_N

### ISSUE THREAD

**Issue by hacknullchainik** [hacknullchainik/DMATH_1306#34]
![image](https://user-images.githubusercontent.com/89996352/161424724-48c6e70b-2195-4906-9bc0-e080aac6d579.png)
![image](https://user-images.githubusercontent.com/89996352/161424727-072788f4-5a28-400e-9c1a-26c4b6f41076.png)

**Comment by MartinIce** [comment]
В функции нет строки print(res) (чекни файл Naturals)

**Comment by MartinIce** [comment]
![Screenshot_3](https://user-images.githubusercontent.com/88541410/161425115-4f13dd95-fa8f-4f22-b341-c6ab45754c9b.png)

**Comment by hacknullchainik** [comment]
суть в том, что у тебя res - тип int а не NNumber, ты используешь больший числа питона

**Comment by hacknullchainik** [comment]
print() - я добавил, чтобы посмотреть значения res

**Comment by MartinIce** [comment]
Из-за особенностей функции Сани (где он возвращает первую цифру деления, умноженную на 10^k), не получается нормально работать со списками. Мы тестили это вместе с Саней на практике по АиГу вроде

**Comment by hacknullchainik** [comment]
понял, окей. Надо уточник у Позднякова. Скорее всего придётся переписывать это всё на нашу арифметику
