### ISSUE TITLE
DIV_QQ_Q не работает

### ISSUE THREAD

**Issue by hacknullchainik** [hacknullchainik/DMATH_1306#36]
![image](https://user-images.githubusercontent.com/89996352/161431180-7d65d422-af1a-4ebe-8709-a95422f94f6d.png)
![image](https://user-images.githubusercontent.com/89996352/161431189-3c12dd9e-3ed3-4efe-9deb-989712615796.png)

**Comment by W1nt3ryyy** [comment]
все работает, исправил
