### ISSUE TITLE
LCM_NN_N incorrect value returned

### ISSUE THREAD

**Issue by doal116** [hacknullchainik/DMATH_1306#38]
LCM for 643 and 788 should be 506684 but the function returns 486684
![image](https://user-images.githubusercontent.com/90492542/161435715-18b6f44c-65cd-4dec-907f-b2a575890b2d.png)

**Comment by W1nt3ryyy** [comment]
fixed

**Comment by doal116** [comment]
Changes pushed?

**Comment by W1nt3ryyy** [comment]
yep

**Comment by doal116** [comment]
LCM of  960 and 550 should be 52800 but the function returns 0
![image](https://user-images.githubusercontent.com/90492542/161443971-cea8d2bd-3fca-4656-9d2e-3dc6e48a56c7.png)
