### ISSUE TITLE
MUL_NN_N ломается на больших числах

### ISSUE THREAD

**Issue by hacknullchainik** [hacknullchainik/DMATH_1306#40]
![image](https://user-images.githubusercontent.com/89996352/161438519-fb3f5507-ea57-4fd2-84e1-8eba478ad67f.png)

**Comment by hacknullchainik** [comment]
![image](https://user-images.githubusercontent.com/89996352/161438596-3fc00acd-127a-4fef-819f-f1c08c036984.png)

**Comment by hellsys** [comment]
жду пока Алекс починит свою функцию, она ломается не на больших, а на определенных цифрах
