### ISSUE TITLE
MUL_ZZ_Z

### ISSUE THREAD

**Issue by doal116** [hacknullchainik/DMATH_1306#41]
313 x 18  = 5634 but MUL_ZZ_Z returns 27234.
![image](https://user-images.githubusercontent.com/90492542/161438786-580c630e-f778-483d-bab8-bbd34d2e0c2f.png)

**Comment by hellsys** [comment]
fixed
![image](https://user-images.githubusercontent.com/94673102/161441460-4707ca35-7af6-4c8b-b5e3-0b9305c543ff.png)

**Comment by doal116** [comment]
116 x 19 = 2204 but function returns 10304
![image](https://user-images.githubusercontent.com/90492542/161442003-48ff0df3-07d2-4eb6-93ff-7713183c69b1.png)

**Comment by hellsys** [comment]
it works...

![image](https://user-images.githubusercontent.com/94673102/161442514-815448d3-d6de-48b7-bc02-e11c0ac100e0.png)

**Comment by hellsys** [comment]
by the way i didn't change anything. the problem was in the MUL_ND_N function

**Comment by doal116** [comment]
oh good then
