### ISSUE TITLE
MUL_ND_N

### ISSUE THREAD

**Issue by hellsys** [hacknullchainik/DMATH_1306#42]
313*8 = 2504 but MUL_ND_N returns 24104
![Screenshot_1](https://user-images.githubusercontent.com/94673102/161439667-0343aa3d-7b71-4dbc-b24f-67b2e48c1c31.png)

**Comment by doal116** [comment]
aight, going to find out why

**Comment by doal116** [comment]
corrected
![image](https://user-images.githubusercontent.com/90492542/161440806-7ce5155b-8ee1-4b24-9a2d-06e272bbdec0.png)
